# Generated by Django 6.0.5 on 2026-05-21 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "tracking_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=60)),
                ("applicant_email", models.EmailField(db_index=True, max_length=60)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("RECORDATION", "Recordation"),
                            ("RENEWAL", "Renewal"),
                            ("CHANGE_OF_OWNERSHIP", "Change of Ownership"),
                            ("CHANGE_OF_NAME", "Change of Name"),
                            ("DISCONTINUATION", "Discontinuation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("NEEDS_MORE_INFORMATION", "Needs More Information"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_started", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer_comments",
                    models.TextField(blank=True, default="", max_length=60),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
        ),
    ]
