# Generated by Django 6.0.5 on 2026-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="reviewer_comments",
            field=models.TextField(blank=True, default="", max_length=60, null=True),
        ),
    ]
